### PR TITLE
Patch for the close event and stdin usage issue

### PR DESCRIPTION
**Pull request by davehayes**
So I got tired of this failing randomly and tried to work with this a bit. This is what I came up with. Let me know if there are any questions or if I need to do more here. Thanks.

### CODE REVIEW

**Comment by davehayes** [comment]
Is the fact that Mojo::Base is not found my pull request's issue or travis's issue?

**Comment by jhthorsen** [comment]
I wonder if this has been fixed by 34929ea now? If not, please rebase and fix the conflicts.

**Comment by davehayes** [comment]
I doubt it has been fixed. I spent a decent amount of time trying to fix this, and wound up coding around the problem at a higher level. When you say "rebase", are you referring to 'git rebase' and what exactly do you mean?

**Comment by jhthorsen** [comment]
I meant "git rebase".

I'm sorry, but I'm going to close this PR since "master" has moved on significantly.

**Pull request closed without merging**
